title: "Metaschema"
baseURL: https://framework.metaschema.dev/
defaultContentLanguage: en
languageCode: "en-us"
MetaDataFormat: "yaml"
googleAnalytics: 
enableGitInfo: true
enableRobotsTXT: true
menu:
  secondary:
    - name: Get involved
      url: /contribute/
    - name: Contact Us
      url: /contribute/contact/
    - name: Github
      url: https://github.com/metaschema-framework/metaschema
#
# Configuration for uswds-hugo
#
module:
  mounts:
  - source: static
    target: static
  - source: static/img
    target: assets/img
  - source: ../examples
    target: static/examples
  imports:
    - path: "github.com/GSA/uswds-hugo"
enableGitInfo: true # enable to get page modification dates for a site stored in Git
params:
  header:
    project_shortname: "Metaschema"
    project_name: "Metaschema Information Modeling Framework"
  contentRepoPath: https://github.com/metaschema-framework/metaschema/tree/master/website/content
  usabanner: false
markup:
  goldmark: # Markdown Rendering
    renderer:
      unsafe: true # required for the Hugo USWDS theme
  highlight: # Code Highlighting
    guessSyntax: true
    noClasses: false # enables USWDS styled syntax highlighting
